apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: drone-ci

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-deploy
  namespace: drone-ci
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get","list","patch","update","create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-deploy
  namespace: drone-ci
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: drone-ci
roleRef:
  kind: Role
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-deploy
  namespace: default
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: drone-ci
roleRef:
  kind: Role
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io

#--- 

#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: drone-deploy
#rules:
#  - apiGroups: ["", "apps", "extensions"]
#    resources: ["deployments"]
   # verbs: ["get","list","patch","update","create"]
